'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Data
Imports System.Runtime.Serialization


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.allscripts.com/Unity", ConfigurationName:="IUnityService")>  _
Public Interface IUnityService
    
    'CODEGEN: Parameter 'MagicResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://www.allscripts.com/Unity/IUnityService/Magic", ReplyAction:="http://www.allscripts.com/Unity/IUnityService/MagicResponse"),  _
     System.ServiceModel.FaultContractAttribute(GetType(Allscripts.UAI.Unity.UnityService.UnityFault), Action:="http://www.allscripts.com/Unity/IUnityService/MagicUnityFaultFault", Name:="UnityFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService"),  _
     System.ServiceModel.XmlSerializerFormatAttribute()>  _
    Function Magic(ByVal request As MagicRequest) As MagicResponse
    
    'CODEGEN: Parameter 'o' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://www.allscripts.com/Unity/IUnityService/ReturnMagicJSON", ReplyAction:="http://www.allscripts.com/Unity/IUnityService/ReturnMagicJSONResponse"),  _
     System.ServiceModel.FaultContractAttribute(GetType(Allscripts.UAI.Unity.UnityService.UnityFault), Action:="http://www.allscripts.com/Unity/IUnityService/ReturnMagicJSONUnityFaultFault", Name:="UnityFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService"),  _
     System.ServiceModel.XmlSerializerFormatAttribute()>  _
    Function ReturnMagicJSON(ByVal request As ReturnMagicJSONRequest) As ReturnMagicJSONResponse
    
    'CODEGEN: Parameter 'GetSecurityTokenResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://www.allscripts.com/Unity/IUnityService/GetSecurityToken", ReplyAction:="http://www.allscripts.com/Unity/IUnityService/GetSecurityTokenResponse"),  _
     System.ServiceModel.FaultContractAttribute(GetType(Allscripts.UAI.Unity.UnityService.UnityFault), Action:="http://www.allscripts.com/Unity/IUnityService/GetSecurityTokenUnityFaultFault", Name:="UnityFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService"),  _
     System.ServiceModel.XmlSerializerFormatAttribute()>  _
    Function GetSecurityToken(ByVal request As GetSecurityTokenRequest) As GetSecurityTokenResponse
    
    'CODEGEN: Parameter 'GetValidSecurityTokenResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityToken", ReplyAction:="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityTokenResponse"),  _
     System.ServiceModel.FaultContractAttribute(GetType(Allscripts.UAI.Unity.UnityService.UnityFault), Action:="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityTokenUnityFaultFaul"& _ 
        "t", Name:="UnityFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService"),  _
     System.ServiceModel.XmlSerializerFormatAttribute()>  _
    Function GetValidSecurityToken(ByVal request As GetValidSecurityTokenRequest) As GetValidSecurityTokenResponse
    
    'CODEGEN: Parameter 'ti' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityTokenPost", ReplyAction:="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityTokenPostResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute()>  _
    Function GetValidSecurityTokenPost(ByVal request As GetValidSecurityTokenPostRequest) As GetValidSecurityTokenPostResponse
    
    'CODEGEN: Parameter 'ti' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://www.allscripts.com/Unity/IUnityService/GetTokenJsonPost", ReplyAction:="http://www.allscripts.com/Unity/IUnityService/GetTokenJsonPostResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute()>  _
    Function GetTokenJsonPost(ByVal request As GetTokenJsonPostRequest) As GetTokenJsonPostResponse
    
    'CODEGEN: Parameter 'ri' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://www.allscripts.com/Unity/IUnityService/RetireSecurityTokenPost", ReplyAction:="http://www.allscripts.com/Unity/IUnityService/RetireSecurityTokenPostResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute()>  _
    Function RetireSecurityTokenPost(ByVal request As RetireSecurityTokenPostRequest) As RetireSecurityTokenPostResponse
    
    'CODEGEN: Parameter 'ri' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://www.allscripts.com/Unity/IUnityService/RetireTokenJsonPost", ReplyAction:="http://www.allscripts.com/Unity/IUnityService/RetireTokenJsonPostResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute()>  _
    Function RetireTokenJsonPost(ByVal request As RetireTokenJsonPostRequest) As RetireTokenJsonPostResponse
    
    'CODEGEN: Parameter 'Token' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://www.allscripts.com/Unity/IUnityService/RetireSecurityToken", ReplyAction:="http://www.allscripts.com/Unity/IUnityService/RetireSecurityTokenResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute()>  _
    Function RetireSecurityToken(ByVal request As RetireSecurityTokenRequest) As RetireSecurityTokenResponse
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Magic", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class MagicRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Action As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=1),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public UserID As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=2),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Appname As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=3),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public PatientID As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=4),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Token As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=5),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Parameter1 As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=6),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Parameter2 As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=7),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Parameter3 As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=8),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Parameter4 As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=9),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Parameter5 As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=10),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Parameter6 As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=11),  _
     System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
    Public data() As Byte
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Action As String, ByVal UserID As String, ByVal Appname As String, ByVal PatientID As String, ByVal Token As String, ByVal Parameter1 As String, ByVal Parameter2 As String, ByVal Parameter3 As String, ByVal Parameter4 As String, ByVal Parameter5 As String, ByVal Parameter6 As String, ByVal data() As Byte)
        MyBase.New
        Me.Action = Action
        Me.UserID = UserID
        Me.Appname = Appname
        Me.PatientID = PatientID
        Me.Token = Token
        Me.Parameter1 = Parameter1
        Me.Parameter2 = Parameter2
        Me.Parameter3 = Parameter3
        Me.Parameter4 = Parameter4
        Me.Parameter5 = Parameter5
        Me.Parameter6 = Parameter6
        Me.data = data
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="MagicResponse", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class MagicResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public MagicResult As System.Data.DataSet
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal MagicResult As System.Data.DataSet)
        MyBase.New
        Me.MagicResult = MagicResult
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")>  _
Partial Public Class MagicInput
    
    Private actionField As String
    
    Private appnameField As String
    
    Private appUserIDField As String
    
    Private patientIDField As String
    
    Private tokenField As String
    
    Private parameter1Field As String
    
    Private parameter2Field As String
    
    Private parameter3Field As String
    
    Private parameter4Field As String
    
    Private parameter5Field As String
    
    Private parameter6Field As String
    
    Private dataField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
    Public Property Action() As String
        Get
            Return Me.actionField
        End Get
        Set
            Me.actionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
    Public Property Appname() As String
        Get
            Return Me.appnameField
        End Get
        Set
            Me.appnameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
    Public Property AppUserID() As String
        Get
            Return Me.appUserIDField
        End Get
        Set
            Me.appUserIDField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
    Public Property PatientID() As String
        Get
            Return Me.patientIDField
        End Get
        Set
            Me.patientIDField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
    Public Property Token() As String
        Get
            Return Me.tokenField
        End Get
        Set
            Me.tokenField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
    Public Property Parameter1() As String
        Get
            Return Me.parameter1Field
        End Get
        Set
            Me.parameter1Field = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=6)>  _
    Public Property Parameter2() As String
        Get
            Return Me.parameter2Field
        End Get
        Set
            Me.parameter2Field = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=7)>  _
    Public Property Parameter3() As String
        Get
            Return Me.parameter3Field
        End Get
        Set
            Me.parameter3Field = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=8)>  _
    Public Property Parameter4() As String
        Get
            Return Me.parameter4Field
        End Get
        Set
            Me.parameter4Field = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=9)>  _
    Public Property Parameter5() As String
        Get
            Return Me.parameter5Field
        End Get
        Set
            Me.parameter5Field = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=10)>  _
    Public Property Parameter6() As String
        Get
            Return Me.parameter6Field
        End Get
        Set
            Me.parameter6Field = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=11)>  _
    Public Property Data() As String
        Get
            Return Me.dataField
        End Get
        Set
            Me.dataField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")>  _
Partial Public Class RetireTokenJsonInput
    
    Private appnameField As String
    
    Private tokenField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
    Public Property Appname() As String
        Get
            Return Me.appnameField
        End Get
        Set
            Me.appnameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
    Public Property Token() As String
        Get
            Return Me.tokenField
        End Get
        Set
            Me.tokenField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")>  _
Partial Public Class RetireTokenInput
    
    Private appnameField As String
    
    Private tokenField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
    Public Property Appname() As String
        Get
            Return Me.appnameField
        End Get
        Set
            Me.appnameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
    Public Property Token() As String
        Get
            Return Me.tokenField
        End Get
        Set
            Me.tokenField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")>  _
Partial Public Class GetTokenJsonInput
    
    Private originalTokenField As String
    
    Private passwordField As String
    
    Private usernameField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
    Public Property OriginalToken() As String
        Get
            Return Me.originalTokenField
        End Get
        Set
            Me.originalTokenField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
    Public Property Password() As String
        Get
            Return Me.passwordField
        End Get
        Set
            Me.passwordField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
    Public Property Username() As String
        Get
            Return Me.usernameField
        End Get
        Set
            Me.usernameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")>  _
Partial Public Class GetTokenInput
    
    Private originalTokenField As String
    
    Private passwordField As String
    
    Private usernameField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
    Public Property OriginalToken() As String
        Get
            Return Me.originalTokenField
        End Get
        Set
            Me.originalTokenField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
    Public Property Password() As String
        Get
            Return Me.passwordField
        End Get
        Set
            Me.passwordField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
    Public Property Username() As String
        Get
            Return Me.usernameField
        End Get
        Set
            Me.usernameField = value
        End Set
    End Property
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="ReturnMagicJSON", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class ReturnMagicJSONRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public o As MagicInput
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal o As MagicInput)
        MyBase.New
        Me.o = o
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="ReturnMagicJSONResponse", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class ReturnMagicJSONResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0)>  _
    Public ReturnMagicJSONResult As System.IO.Stream
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal ReturnMagicJSONResult As System.IO.Stream)
        MyBase.New
        Me.ReturnMagicJSONResult = ReturnMagicJSONResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetSecurityToken", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class GetSecurityTokenRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Username As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=1),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Password As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Username As String, ByVal Password As String)
        MyBase.New
        Me.Username = Username
        Me.Password = Password
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetSecurityTokenResponse", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class GetSecurityTokenResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetSecurityTokenResult As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetSecurityTokenResult As String)
        MyBase.New
        Me.GetSecurityTokenResult = GetSecurityTokenResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetValidSecurityToken", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class GetValidSecurityTokenRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Username As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=1),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Password As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=2),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public originalToken As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Username As String, ByVal Password As String, ByVal originalToken As String)
        MyBase.New
        Me.Username = Username
        Me.Password = Password
        Me.originalToken = originalToken
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetValidSecurityTokenResponse", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class GetValidSecurityTokenResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetValidSecurityTokenResult As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetValidSecurityTokenResult As String)
        MyBase.New
        Me.GetValidSecurityTokenResult = GetValidSecurityTokenResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetValidSecurityTokenPost", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class GetValidSecurityTokenPostRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public ti As GetTokenInput
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal ti As GetTokenInput)
        MyBase.New
        Me.ti = ti
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetValidSecurityTokenPostResponse", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class GetValidSecurityTokenPostResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0)>  _
    Public GetValidSecurityTokenPostResult As System.IO.Stream
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetValidSecurityTokenPostResult As System.IO.Stream)
        MyBase.New
        Me.GetValidSecurityTokenPostResult = GetValidSecurityTokenPostResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetTokenJsonPost", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class GetTokenJsonPostRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public ti As GetTokenJsonInput
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal ti As GetTokenJsonInput)
        MyBase.New
        Me.ti = ti
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetTokenJsonPostResponse", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class GetTokenJsonPostResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0)>  _
    Public GetTokenJsonPostResult As System.IO.Stream
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetTokenJsonPostResult As System.IO.Stream)
        MyBase.New
        Me.GetTokenJsonPostResult = GetTokenJsonPostResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="RetireSecurityTokenPost", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class RetireSecurityTokenPostRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public ri As RetireTokenInput
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal ri As RetireTokenInput)
        MyBase.New
        Me.ri = ri
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="RetireSecurityTokenPostResponse", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class RetireSecurityTokenPostResponse
    
    Public Sub New()
        MyBase.New
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="RetireTokenJsonPost", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class RetireTokenJsonPostRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public ri As RetireTokenJsonInput
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal ri As RetireTokenJsonInput)
        MyBase.New
        Me.ri = ri
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="RetireTokenJsonPostResponse", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class RetireTokenJsonPostResponse
    
    Public Sub New()
        MyBase.New
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="RetireSecurityToken", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class RetireSecurityTokenRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Token As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.allscripts.com/Unity", Order:=1),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Appname As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Token As String, ByVal Appname As String)
        MyBase.New
        Me.Token = Token
        Me.Appname = Appname
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="RetireSecurityTokenResponse", WrapperNamespace:="http://www.allscripts.com/Unity", IsWrapped:=true)>  _
Partial Public Class RetireSecurityTokenResponse
    
    Public Sub New()
        MyBase.New
    End Sub
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Public Interface IUnityServiceChannel
    Inherits IUnityService, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Partial Public Class UnityServiceClient
    Inherits System.ServiceModel.ClientBase(Of IUnityService)
    Implements IUnityService
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IUnityService_Magic(ByVal request As MagicRequest) As MagicResponse Implements IUnityService.Magic
        Return MyBase.Channel.Magic(request)
    End Function
    
    Public Function Magic(ByVal Action As String, ByVal UserID As String, ByVal Appname As String, ByVal PatientID As String, ByVal Token As String, ByVal Parameter1 As String, ByVal Parameter2 As String, ByVal Parameter3 As String, ByVal Parameter4 As String, ByVal Parameter5 As String, ByVal Parameter6 As String, ByVal data() As Byte) As System.Data.DataSet
        Dim inValue As MagicRequest = New MagicRequest
        inValue.Action = Action
        inValue.UserID = UserID
        inValue.Appname = Appname
        inValue.PatientID = PatientID
        inValue.Token = Token
        inValue.Parameter1 = Parameter1
        inValue.Parameter2 = Parameter2
        inValue.Parameter3 = Parameter3
        inValue.Parameter4 = Parameter4
        inValue.Parameter5 = Parameter5
        inValue.Parameter6 = Parameter6
        inValue.data = data
        Dim retVal As MagicResponse = CType(Me,IUnityService).Magic(inValue)
        Return retVal.MagicResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IUnityService_ReturnMagicJSON(ByVal request As ReturnMagicJSONRequest) As ReturnMagicJSONResponse Implements IUnityService.ReturnMagicJSON
        Return MyBase.Channel.ReturnMagicJSON(request)
    End Function
    
    Public Function ReturnMagicJSON(ByVal o As MagicInput) As System.IO.Stream
        Dim inValue As ReturnMagicJSONRequest = New ReturnMagicJSONRequest
        inValue.o = o
        Dim retVal As ReturnMagicJSONResponse = CType(Me,IUnityService).ReturnMagicJSON(inValue)
        Return retVal.ReturnMagicJSONResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IUnityService_GetSecurityToken(ByVal request As GetSecurityTokenRequest) As GetSecurityTokenResponse Implements IUnityService.GetSecurityToken
        Return MyBase.Channel.GetSecurityToken(request)
    End Function
    
    Public Function GetSecurityToken(ByVal Username As String, ByVal Password As String) As String
        Dim inValue As GetSecurityTokenRequest = New GetSecurityTokenRequest
        inValue.Username = Username
        inValue.Password = Password
        Dim retVal As GetSecurityTokenResponse = CType(Me,IUnityService).GetSecurityToken(inValue)
        Return retVal.GetSecurityTokenResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IUnityService_GetValidSecurityToken(ByVal request As GetValidSecurityTokenRequest) As GetValidSecurityTokenResponse Implements IUnityService.GetValidSecurityToken
        Return MyBase.Channel.GetValidSecurityToken(request)
    End Function
    
    Public Function GetValidSecurityToken(ByVal Username As String, ByVal Password As String, ByVal originalToken As String) As String
        Dim inValue As GetValidSecurityTokenRequest = New GetValidSecurityTokenRequest
        inValue.Username = Username
        inValue.Password = Password
        inValue.originalToken = originalToken
        Dim retVal As GetValidSecurityTokenResponse = CType(Me,IUnityService).GetValidSecurityToken(inValue)
        Return retVal.GetValidSecurityTokenResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IUnityService_GetValidSecurityTokenPost(ByVal request As GetValidSecurityTokenPostRequest) As GetValidSecurityTokenPostResponse Implements IUnityService.GetValidSecurityTokenPost
        Return MyBase.Channel.GetValidSecurityTokenPost(request)
    End Function
    
    Public Function GetValidSecurityTokenPost(ByVal ti As GetTokenInput) As System.IO.Stream
        Dim inValue As GetValidSecurityTokenPostRequest = New GetValidSecurityTokenPostRequest
        inValue.ti = ti
        Dim retVal As GetValidSecurityTokenPostResponse = CType(Me,IUnityService).GetValidSecurityTokenPost(inValue)
        Return retVal.GetValidSecurityTokenPostResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IUnityService_GetTokenJsonPost(ByVal request As GetTokenJsonPostRequest) As GetTokenJsonPostResponse Implements IUnityService.GetTokenJsonPost
        Return MyBase.Channel.GetTokenJsonPost(request)
    End Function
    
    Public Function GetTokenJsonPost(ByVal ti As GetTokenJsonInput) As System.IO.Stream
        Dim inValue As GetTokenJsonPostRequest = New GetTokenJsonPostRequest
        inValue.ti = ti
        Dim retVal As GetTokenJsonPostResponse = CType(Me,IUnityService).GetTokenJsonPost(inValue)
        Return retVal.GetTokenJsonPostResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IUnityService_RetireSecurityTokenPost(ByVal request As RetireSecurityTokenPostRequest) As RetireSecurityTokenPostResponse Implements IUnityService.RetireSecurityTokenPost
        Return MyBase.Channel.RetireSecurityTokenPost(request)
    End Function
    
    Public Sub RetireSecurityTokenPost(ByVal ri As RetireTokenInput)
        Dim inValue As RetireSecurityTokenPostRequest = New RetireSecurityTokenPostRequest
        inValue.ri = ri
        Dim retVal As RetireSecurityTokenPostResponse = CType(Me,IUnityService).RetireSecurityTokenPost(inValue)
    End Sub
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IUnityService_RetireTokenJsonPost(ByVal request As RetireTokenJsonPostRequest) As RetireTokenJsonPostResponse Implements IUnityService.RetireTokenJsonPost
        Return MyBase.Channel.RetireTokenJsonPost(request)
    End Function
    
    Public Sub RetireTokenJsonPost(ByVal ri As RetireTokenJsonInput)
        Dim inValue As RetireTokenJsonPostRequest = New RetireTokenJsonPostRequest
        inValue.ri = ri
        Dim retVal As RetireTokenJsonPostResponse = CType(Me,IUnityService).RetireTokenJsonPost(inValue)
    End Sub
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IUnityService_RetireSecurityToken(ByVal request As RetireSecurityTokenRequest) As RetireSecurityTokenResponse Implements IUnityService.RetireSecurityToken
        Return MyBase.Channel.RetireSecurityToken(request)
    End Function
    
    Public Sub RetireSecurityToken(ByVal Token As String, ByVal Appname As String)
        Dim inValue As RetireSecurityTokenRequest = New RetireSecurityTokenRequest
        inValue.Token = Token
        inValue.Appname = Appname
        Dim retVal As RetireSecurityTokenResponse = CType(Me,IUnityService).RetireSecurityToken(inValue)
    End Sub
End Class

Namespace Allscripts.UAI.Unity.UnityService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UnityFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")>  _
    Partial Public Class UnityFault
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private ErrorMessageField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.ErrorMessageField
            End Get
            Set
                Me.ErrorMessageField = value
            End Set
        End Property
    End Class
End Namespace
